creazione documento analisi dei requisiti
tech-wave-swe/tech-wave-swe.github.io pull request #30
Opened 2024-12-13 17:10 UTC by gaiapistori

2024-12-14 11:01 UTC, LucaMonetti commented on docs/docs/RTB/Analisi dei requisiti.md
> +		2.3.2 Requisiti tecnici opzionali
Non è necessaria la creazione di un TOC a mano. Diventa difficile da gestire al crescere del documento. Docusaurus implementa già una TOC nella sidebar "laterale", per averne una anche all'inizio del documento è possibile inserire:

```suggestion
import TOCInline from '@theme/TOCInline';
<TOCInline toc={toc} />
```

Eventualmente modificando l'estensione del file in .mdx

2024-12-14 11:29 UTC, LucaMonetti requested changes
Ho inserito alcune modifiche. Tra cui il TOC iniziale. 

Prima di fare la merge su main è necessario fare la merge su develop per evitare inconsistenze.

2024-12-14 11:29 UTC, LucaMonetti commented on docs/docs/RTB/Analisi dei requisiti.md
> +		2.3.2 Requisiti tecnici opzionali
Non è necessaria la creazione di un TOC a mano. Diventa difficile da gestire al crescere del documento. Docusaurus implementa già una TOC nella sidebar "laterale", per averne una anche all'inizio del documento è possibile inserire:

```suggestion
import TOCInline from '@theme/TOCInline';
<TOCInline toc={toc} />
```

Eventualmente modificando l'estensione del file in .mdx

2024-12-14 11:29 UTC, LucaMonetti commented on docs/docs/RTB/Analisi dei requisiti.md
> +- L'applicativo deve permettere di impostare il suo ambiente di lavoro indicato il file dei requisiti e la cartella con il codice scritto dagli sviluppatori in C / C++dove effettuare il controllo uti
```suggestion
- L'applicativo deve permettere di impostare il suo ambiente di lavoro indicando il file dei requisiti e la cartella con il codice scritto dagli sviluppatori in C / C++ dove effettuare il controllo utilizzando una semplice interfaccia grafica.
```

2024-12-14 11:29 UTC, LucaMonetti commented on docs/docs/RTB/Analisi dei requisiti.md
> +- L'applicativo deve, una volta ottenuti i requisiti, avviare un processo di ricerca (in buona parte svolto da un LLM) nella cartella, contenente i file di codice, per generare in output la lista dei
```suggestion
- L'applicativo deve, una volta ottenuti i requisiti, avviare un processo di ricerca nella cartella contenente i file di codice producendo in output una lista che associa ogni requisito con il suo stato di implementazione. Per stato di implementazione si intende: il testo del requisito, la sua descrizione e una indicazione sul frammento di codice (funzione o parte di essa) dove potrebbe essere implementato. La ricerca si articolerà in due fasi: una prima fase di filtro, in cui verranno selezionati i file con maggiore probabilità di contenere l'implementazione del requisito, e una seconda fase, eseguita tramite LLM, per individuare con precisione la posizione all'interno del file.
```

2024-12-14 11:29 UTC, LucaMonetti commented on docs/docs/RTB/Analisi dei requisiti.md
> +- L'applicativo deve essere in grado di estrapolare le informazioni necessarie all'analisi a partire da un file dei requisiti in formato *.requif*.
```suggestion
- L'applicativo deve essere in grado di estrapolare le informazioni necessarie all'analisi a partire da un file dei requisiti in formato *.reqif*.
```

2024-12-14 11:33 UTC, LucaMonetti requested changes
Ho fatto alcune modifiche, tra cui la presenza del TOC.

Prima di fare il merge su main è necessario fare il merge su develop per evitare inconsistenze.

2024-12-15 13:39 UTC, gaiapistori commented
applicate le modifiche e cambiata l'estensione del file

2024-12-16 10:15 UTC, gaiapistori commented
fatto merge su develop

2024-12-16 10:16 UTC, gaiapistori reviewed
modifiche visionate

2024-12-16 16:23 UTC, merged

2024-12-16 16:23 UTC, LucaMonetti approved these changes
LGTM!